### ISSUE TITLE
Unable to verify signature 

### ISSUE THREAD

**Issue by jkbbwr** [joken-elixir/joken#380]
Trying to sign something with PS256 but failing to verify the signature in either Python or Javascript.

```elixir
defmodule DynamicClientRequest do
  use Joken.Config

  @impl true
  def token_config do
    default_claims(iss: "ckWBLOKO6yH4mIDL8WLYXP", aud: "0015800000jfwxXAAQ")
    |> add_claim("application_type", fn -> "web" end, nil)
    |> add_claim("grant_types", fn -> ["authorization_code"] end, nil)
    |> add_claim("software_statement", fn -> File.read!("./certs/ssa") end, nil)
    |> add_claim("token_endpoint_auth_signing_alg", fn -> "PS256" end, nil)
    |> add_claim("request_object_signing_alg", fn -> "PS256" end, nil)
    |> add_claim("id_token_signed_response_alg", fn -> "PS256" end, nil)
    |> add_claim("token_endpoint_auth_method", fn -> "tls_client_auth" end, nil)
  end

  def signer do
    signer =
      Joken.Signer.create("PS256", %{"pem" => File.read!("./certs/seal.pem")}, %{
        "kid" => "A3kLpDUm0lcMeuUgCbxlkXkIx3c"
      })
  end
end
```

I then go to a language say python

```
jwt.decode(encoded, public_key, algorithms=["PS256"])
ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [_OpenSSLErrorWithText(code=151584876, lib=9, reason=108, reason_text=b'error:0909006C:PEM routines:get_name:no start line')])
```
Or javascript
```
jwt --decode --algorithms "PS256" --public-key-file A3kLpDUm0lcMeuUgCbxlkXkIx3c.pem (cat jwt)
JsonWebTokenError: invalid signature
    at /home/jakob/.config/yarn/global/node_modules/jsonwebtoken/verify.js:133:19
    at getSecret (/home/jakob/.config/yarn/global/node_modules/jsonwebtoken/verify.js:90:14)
    at module.exports [as verify] (/home/jakob/.config/yarn/global/node_modules/jsonwebtoken/verify.js:94:10)
    at module.exports (/home/jakob/.config/yarn/global/node_modules/jsonwebtokencli/convert.js:15:33)
    at /home/jakob/.config/yarn/global/node_modules/jsonwebtokencli/main.js:43:12
```

However if I use a JWT generated by a different language, the signatures validate correctly.

**Comment by victorolinasc** [comment]
PS256 has a known bug as described https://github.com/potatosalad/erlang-jose/issues/121#issuecomment-919072956

Can you see that it resolves for you?

**Comment by jkbbwr** [comment]
This fix resolves my issue but I would rather not rely on this too much if I can help it. 

Is this going to be fixed either downstream or here?

**Comment by victorolinasc** [comment]
This can only be fixed downstream unfortunately as it is the way JOSE passes options to RSA crypto. I'll be closing the issue here because we can't solve it on Joken side.
