### ISSUE TITLE
Can't figure out correct setup for signer from documentation

### ISSUE THREAD

**Issue by tomazbracic** [joken-elixir/joken#406]
I am using Keycloak (v.22.x). 
 - Over there I have configured a realm, client and users.
 - client uses RS256 for JWT token. 
 - I can see public_key (which doesn't have this beginning and end) -> so I am wrapping into this. 
              "-----BEGIN PUBLIC KEY-----\n" <> public_key_content <> "\n-----END PUBLIC KEY-----"

I am able to get an access_token (JWT) from remote Keycloak. 

Following documentation I must admit I am not really sure how to approach this as a AUTH beginner. 

`signer = Joken.Signer.create("RS256", pem_public_key)
** (Joken.Error) A map was expected for the key parameter in the signer creation.`

trying differently (found on internet) ... still doesn't work. 

`signer = Joken.Signer.create("RS256", %{key:  pem_public_key})
** (FunctionClauseError) no function clause matching in JOSE.JWK.from_record/1    
    
    The following arguments were given to JOSE.JWK.from_record/1:
    
        # 1
        {:error, {:missing_required_keys, ["keys", "kty"]}}
    
    Attempted function clauses (showing 2 out of 2):
    
        def from_record({:jose_jwk, keys, kty, fields})
        def from_record(list) when is_list(list)
    
    (jose 1.11.6) lib/jose/jwk.ex:35: JOSE.JWK.from_record/1
    (joken 2.6.0) lib/joken/signer.ex:98: Joken.Signer.create/3
    iex:16: (file)`

Can you please help with directions how to create a signer in order to be able to call Joken.verify_and_validate function to get all the claims verified? 

Thanks in advance

**Comment by tomazbracic** [comment]
Ok, for others if you have similar dilema. I did come few steps forward. 

So, setup stays the same as described above. 

```
require Req
url = "http://<IP>:8080/realms/<myrealm>/protocol/openid-connect/token"

params = [
 {"client_id", "myclient"},
 {"grant_type", "password"},
# you can get client_secret if you turn on credentials tab under client setup -> client authentication -> turn on
 {"client_secret", "XiCSci42SCuBCkht5PWZI6Po10hyvC0F"}, 
 {"scope", "openid"},
 {"username", "<my username>"},
 {"password", "<my password>"}
]

headers = [
   {"Content-Type", "application/x-www-form-urlencoded"}
]

# issue a call
response = Req.post!(url, form: params, headers: headers)
%Req.Response{
  status: 200,
  headers: %{
    "cache-control" => ["no-store"],
    "content-type" => ["application/json"],
    "pragma" => ["no-cache"],
    "referrer-policy" => ["no-referrer"],
    "set-cookie" => ["KEYCLOAK_LOCALE=; Version=1; Comment=Expiring cookie; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/tomaztest/; HttpOnly",
     "KC_RESTART=; Version=1; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/realms/tomaztest/; HttpOnly"],
    "strict-transport-security" => ["max-age=31536000; includeSubDomains"],
    "x-content-type-options" => ["nosniff"],
    "x-frame-options" => ["SAMEORIGIN"],
    "x-xss-protection" => ["1; mode=block"]
  },
  body: %{
    "access_token" => "eyJhbGciOiJSUzI1NiIsInR5c     <long string>    Ry68RhJxT19F_tSIj7TCB-2SRTMu9xpC0E-VNXFgw",
    "expires_in" => 300,
    "id_token" => "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAi     <long string>     b6slzNw6VT95bwF1UPNANo3g",
    "not-before-policy" => 0,
    "refresh_expires_in" => 1800,
    "refresh_token" => "eyJhbGciOiJIUzI1NiIsInR5cCIgOiA     <long string>      pslPKq7o8ImkzJ-4mcNGFSSMw",
    "scope" => "openid email profile",
    "session_state" => "e4973bf5-65fd-4044-b293-efd6765d88d4",
    "token_type" => "Bearer"
  },
  trailers: %{},
  private: %{}
}

# great, now we have access_token which is JWT to my understaning. 
# i can check this with 

iex(8)>  Joken.peek_claims(jwt)
{:ok,
 %{
   "acr" => "1",
   "allowed-origins" => ["http://192.168.88.182:8000"],
   "aud" => "account",
   "azp" => "myclient",
   "email" => "<myemail>",
   "email_verified" => true,
   "exp" => 1699602827,
   "iat" => 1699602527,
   "iss" => "http://<keycloka IP>:8080/realms/tomaztest",
   "jti" => "7627f2db-5cc1-49dd-ac11-ec1e0ce55cad",
   "picture" => "https://avatars.githubuser<link to my avatar>",
   "preferred_username" => "tomaz",
   "realm_access" => %{
     "roles" => ["offline_access", "uma_authorization", "myrole",
      "default-roles-tomaztest"]
   },
   "resource_access" => %{
     "account" => %{
       "roles" => ["manage-account", "manage-account-links", "view-profile"]
     }
   },
   "scope" => "openid email profile",
   "session_state" => "e4973bf5-65fd-4044-b293-efd6765d88d4",
   "sid" => "e4973bf5-65fd-4044-b293-efd6765d88d4",
   "sub" => "4ed414b8-fb26-43f1-b4cc-166d0ebe085e",
   "typ" => "Bearer"
 }}


# great for now

# I need KEYCLOAK public key from its endpoint ... 
# For testing in iex I used this form

public_key_pem = """
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BA <long string> r5F0csLOSfGKKsbQIDAQAB
-----END PUBLIC KEY-----
"""

# NOW SIGNER ... I was able to correctly set it up with the help of this link
# https://hexdocs.pm/joken/signers.html#pem-privacy-enhanced-mail

signer = Joken.Signer.create("RS256", %{"pem" => public_key_pem})
%Joken.Signer{
  jwk: #JOSE.JWK<keys: :undefined, fields: %{}, ...>,
  jws: %JOSE.JWS{
    alg: {:jose_jws_alg_rsa_pkcs1_v1_5, :RS256},
    b64: :undefined,
    fields: %{"typ" => "JWT"}
  },
  alg: "RS256"
}

# validation

iex(11)> {:ok, claims} = Testko.Token.verify_and_validate(jwt, signer)

08:51:48.341 [debug] Claim %{"aud" => "account"} did not pass validation.

Current time: 1699602708

** (MatchError) no match of right hand side value: {:error, [message: "Invalid token", claim: "aud", claim_val: "account"]}
    (stdlib 5.1.1) erl_eval.erl:498: :erl_eval.expr/6
    iex:11: (file)
iex(11)> 

```

At least it looks like it is ok, BUT I now get this next error / issue. And I am not sure where this points to. Is this a 
misconfigured Keycloak (though I did minimal setup following the documentation and it works ok. I even successfuly 
validated token via BASH, but here I get this error. 


ANY ADVICE or HELP would be really appreciated.

**Comment by tomazbracic** [comment]
Finishing up, for now. I still need to learn more about claims and their sense. Based on various sources on the internet I came to the conclusion that I can probably skip two of the default claims that Keycloak provides inside its JWT access tokens. "aud" and "iss" 

Based on this "https://hexdocs.pm/joken/common_use_cases.html#signer-fetched-from-another-server" I configured it like this. 

Still need to check this option `use Joken.Config, default_signer: nil # no signer`, but for now it looks like it works. ;)

```
import Joken

@impl true
def token_config do
  default_claims(skip: [:aud, :iss])
  |> add_claim("iss", nil, &(&1 == "http://<IP>:8080/realms/tomaztest"))
  |> add_claim("aud", nil, &(&1 == "account"))
end


# so now I get this

iex(22)> {:ok, claims} = Testko.Token.verify_and_validate(jwt, signer)
{:ok,
 %{
   "acr" => "1",
   "allowed-origins" => ["http://<IP>:8000"],
   "aud" => "account",
   "azp" => "myclient",
   "email" => "<my email>",
   "email_verified" => true,
   "exp" => 1699606216,
   "iat" => 1699605916,
   "iss" => "http://<keycloak ip>:8080/realms/tomaztest",
   "jti" => "6cd49313-d8ba-41d1-8a6d-1b3a24f4ea2d",
   "picture" => "<image url>,
   "preferred_username" => "tomaz",
   "realm_access" => %{
     "roles" => ["offline_access", "uma_authorization", "myrole",
      "default-roles-tomaztest"]
   },
   "resource_access" => %{
     "account" => %{
       "roles" => ["manage-account", "manage-account-links", "view-profile"]
     }
   },
   "scope" => "openid email profile",
   "session_state" => "2abc9084-64a3-43d0-b31c-3e880fc5ec99",
   "sid" => "2abc9084-64a3-43d0-b31c-3e880fc5ec99",
   "sub" => "4ed414b8-fb26-43f1-b4cc-166d0ebe085e",
   "typ" => "Bearer"
 }}
iex(23)> 

```


Can someone here please just confirms that I did this correctly and can close the issue?
Thanks

**Comment by victorolinasc** [comment]
@tomazbracic will close this for now! Feel free to re-open if any other issues arise. Once again, your use case is perfect for `joken_jwks`.
